/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function deploy(localRoot: string, remoteRoot: string, host: string, password: string, user: string, port: string, isDelete: boolean): void
